name: macOS workflow

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: False
      matrix:
        python: [3.6, 3.7]
        os: [macos-10.15]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox
        run: pip install tox

      - name: Run Tox
        run: tox -e py
